POC_V2/Areas/RC/Controllers/RCApplicationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using dal.RC_DAL;
using dal.RC_BO;
using dal;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;
using POC_V2.Areas.RC.Models;
using NSABP_POC.Filters;

namespace POC_V2.Areas.RC.Controllers
{
    [Auth]
    public class RCApplicationController : Controller
    {
        // GET: RC/RCApplication
        #region  views
        [HttpGet]
        public ActionResult RCApp()
        {

            return View();
        }
        public PartialViewResult p_RCApp()
        {
            RCApp_DAL obj = new RCApp_DAL(); HeaderDAL obj1 = new HeaderDAL();
            Personal_DAL obj2 = new Personal_DAL();
            ViewBag.Countries = obj.getCountries();
            ViewBag.States = obj1.GetStates("0");
            ViewBag.GetRegularActivities = obj.GetRegularActivities();
            ViewBag.GetStudyActivities = obj.GetStudyActivities();
            ViewBag.GetDataManagementActivities = obj.GetDataManagementActivities();
            ViewBag.GetPharmacyActivities = obj.GetPharmacyActivities();
            ViewBag.GetMedicalSpecialties = obj.GetMedicalSpecialties();
            ViewBag.Persontype = obj2.GetPerson_Types();
            return PartialView("~/Areas/RC/Views/Shared/p_RCApp.cshtml");
        }
        public ActionResult getAddress()
        {

            return PartialView("~/Areas/RC/Views/Shared/LoadAddress.cshtml");
        }
        public JsonResult lstAddreses()
        {
            RCApp_DAL obj = new RCApp_DAL();

            var lst = obj.lstGetAddresses().ToList();
            return Json(new { data = lst }, JsonRequestBehavior.AllowGet);

        }
        public ActionResult LoadPersonnelDetails()
        {

            return PartialView("/Areas/RC/Views/Shared/P_Load_PersonalDetails.cshtml");
        }
        public JsonResult GetPersonnelDetails()
        {
            Personal_DAL obj = new Personal_DAL();
            var data = obj.GetRCPersonnelDetails();
            return Json(new { data = data.ToList() }, JsonRequestBehavior.AllowGet);
            //return Json(new { data = result , RegularActivities = "'" + RegularActivitiesIDs + "'", StudyActivities = "'" + StudyActivitiesIDs + "'", DataManagementActivities = "'" + DataManagementActivitiesIDs + "'", PharmacyActivities = "'" + PharmacyActivitiesIDs + "'" }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult OpenaddAddresspopup()
        {
            HeaderDAL obj1 = new HeaderDAL();
            obj1.GetStates("usa");
            RCApp_DAL obj = new RCApp_DAL();
            ViewBag.Countries = obj.getCountries();
            ViewBag.States = obj1.GetStates("usa");
            return PartialView("~/Areas/RC/Views/Shared/P_AddAddress.cshtml");
        }
        public ActionResult RCAppDetails()
        {

            return View();
        }
       
        [HttpGet]
        public ActionResult openAddpersonPopup()
        {
            Personal_DAL objperson = new Personal_DAL();
            RCApp_DAL obj = new RCApp_DAL();
            ViewBag.SuffixTypes = obj.GetSuffix();

            ViewBag.Status = objperson.GetPersonnelStatus();

            ViewBag.Persontype = objperson.GetPerson_Types();
            ViewBag.Degrees = obj.GetDegree();
            ViewBag.MedicalSpeciality = objperson.GetMedicalSpecialties(1);

            return PartialView("~/Areas/RC/Views/Shared/P_AddPersonadetails.cshtml");
        }

        public PartialViewResult p_Addendums()
        {
            RCApp_DAL obj = new RCApp_DAL();
            HeaderDAL obj1 = new HeaderDAL();
            Personal_DAL obj2 = new Personal_DAL();
            ViewBag.Countries = obj.getCountries();
            ViewBag.States = obj1.GetStates("0");
            ViewBag.GetRegularActivities = obj.GetRegularActivities();
            ViewBag.GetStudyActivities = obj.GetStudyActivities();
            ViewBag.GetDataManagementActivities = obj.GetDataManagementActivities();
            ViewBag.GetPharmacyActivities = obj.GetPharmacyActivities();
            ViewBag.GetMedicalSpecialties = obj.GetMedicalSpecialties();
            ViewBag.Persontype = obj2.GetPerson_Types();
            return PartialView("~/Areas/RC/Views/RCApplication/p_Addendums.cshtml");
        }
        #endregion
        public JsonResult SaveSiteAddendumDetails(RCAppAddendumSave obj, bool isresubmit)
        {
            string res = "";
            try
            {
                RCApp_DAL dal = new RCApp_DAL();
                obj._T006_Research_Site.CreatedBy = Convert.ToInt16(Session["UserId"]);
                obj._T006_Research_Site.ModifiedBy = Convert.ToInt16(Session["UserId"]);
                obj._T006_Research_Site.CreatedOn = DateTime.Today.Date;
                obj._T006_Research_Site.ModifiedOn = DateTime.Today.Date;
                if (dal.SaveSiteAddendumDetails(obj, isresubmit))
                {
                    res = "Addendum details created successfully.";
                }
                else
                {
                    res = "Invalid operation";
                }
            }
            catch (Exception ex)
            {
                res = "Invalid operation";
                throw;
            }
            return Json(res, JsonRequestBehavior.AllowGet);
        }
        public JsonResult EditRCApp(int id)
        {
            RCApp_DAL obj = new RCApp_DAL();
            var res = obj.ViewRCDetails(id);
            return Json(new { data = res }, JsonRequestBehavior.AllowGet);
            //return Json(new { data = result , RegularActivities = "'" + RegularActivitiesIDs + "'", StudyActivities = "'" + StudyActivitiesIDs + "'", DataManagementActivities = "'" + DataManagementActivitiesIDs + "'", PharmacyActivities = "'" + PharmacyActivitiesIDs + "'" }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult getRcAppDetails()
        {
            RCApp_DAL dal = new RCApp_DAL();
            var res = dal.getRCDetails();
            return Json(new { data = res });
        }
        public JsonResult SaveRcApp(RCAppSave obj)
        {
            string res = "";
            int id;
            try
            {
                RCApp_DAL dal = new RCApp_DAL();
                if(TempData["fileByte"]!=null)
                {
                    obj._T001_Research_Collaborator.Audits_Attachment = (byte[])TempData["fileByte"];
                }
                
                obj._T001_Research_Collaborator.CreatedBy = Convert.ToInt16(Session["UserId"]);
                obj._T001_Research_Collaborator.ModifiedBy = Convert.ToInt16(Session["UserId"]);
                obj._T001_Research_Collaborator.CreatedOn = DateTime.Today.Date;
                obj._T001_Research_Collaborator.ModifiedOn = DateTime.Today.Date;
                id = dal.SaveRcApp(obj);
                if (id > 0)
                {
                    res = "Rc details saved successfully.";
                }
                else
                {
                    res = "Invalid operation";
                }
            }
            catch (Exception ex)
            {
                res = "Invalid operation";
                throw;
            }
            return Json(new { res = res, id = id }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult UpadteRcApp(RCAppSave obj)
        {
            int id = obj._T001_Research_Collaborator.ID;
            string res = "";
            try
            {
                RCApp_DAL dal = new RCApp_DAL();

                obj._T001_Research_Collaborator.ModifiedBy = Convert.ToInt16(Session["UserId"]);

                obj._T001_Research_Collaborator.ModifiedOn = DateTime.Today.Date;
                if (TempData["fileByte"] != null)
                {
                    obj._T001_Research_Collaborator.Audits_Attachment = (byte[])TempData["fileByte"];
                }
                if (dal.UpdateRCApp(obj))
                {
                    res = "Rc details updated successfully.";
                }
                else
                {
                    res = "Invalid operation";
                }
            }
            catch (Exception ex)
            {
                res = "Invalid operation";
                throw;
            }
            return Json(new { res = res, id = id }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult SaveAddress(T213_Address obj)
        {
            string result = "";
            obj.CreatedBy = Convert.ToInt16(Session["UserId"]);
            obj.ModifiedBy = Convert.ToInt16(Session["UserId"]);
            obj.CreatedOn = DateTime.Today.Date;
            obj.ModifiedOn = DateTime.Today.Date;
            HeaderDAL objdal = new HeaderDAL();
            try
            {
                if (!objdal.isAddressExist(obj))
                {
                    if (objdal.SaveAddresses(obj))
                    {
                        result = "Success";
                    }
                    else
                    {
                        result = "invalid";
                    }
                }
                else
                {
                    result = "Address existed";
                }
            }
            catch (Exception ex)
            {

            }
            return Json(new { data = result });
        }
        public JsonResult UpdateAddressdetails(T213_Address obj)
        {
            string result = "";
            obj.ModifiedBy = Convert.ToInt16(Session["UserId"]);
            obj.ModifiedOn = DateTime.Today.Date;
            HeaderDAL objdal = new HeaderDAL();
            try
            {
                if (!objdal.isAddressExist(obj))
                {
                    if (objdal.UpdateAddress(obj))
                    {
                        result = "Success";
                    }
                    else
                    {
                        result = "invalid";
                    }

POC_V2/Areas/RC/Views/Shared/LoadAddress.cshtml
@*@model IEnumerable<dal.sp_GetAddressDetails_Result>*@
<div>
    <div>
        <table id="tblAddress" class="display nowrap table table-hover table-responsive table-striped table-bordered" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>
                        <i id="i_expnd" style="color:indianred;font-weight:bold" class="ti-arrow-circle-right" data-toggle="tooltip" title="Expand/Collpase"></i>
                    </th>
                    <th>Select</th>
                    <th>Edit</th>
                    <th>View</th>
                    <th>Address ID</th>
                    <th>Address Line1</th>
                    <th>Address Line2</th>
                    <th>Country Name</th>
                    <th>State Name</th>
                    <th>City</th>
                    <th>ZIP</th>
                    <th>Attention</th>
                    <th>Department</th>
                    <th>Internal Office</th>
                </tr>
            </thead>
        </table>
    </div>
    <div class="offset-4">
        <input type="button" value="Add Address" id="btnAddaddress" class="btn btn-info" />
        <input type="button" value="Load" id="LoadAddress" class="btn btn-info" />
        <input type="button" id="LoadAddressCancel" value="Cancel" class="btn btn-info" data-dismiss-modal="#AddressModal" />
    </div>
</div>


<script>
    function PopAddress(id) {
       
        var table = $('#tblAddress').DataTable();
        var tr = id.closest('tr');
        var data = table.row(tr).data();
        var url = "/RCApplication/OpenaddAddresspopup";
        $("#add_AddressModalBody").load(url, function () {
            $("#btnUpdate").show();
            $("#btnSave").hide();
            $("#Addressid").val(data["Address_ID"]);
            $("#txtAddress1").val(data["Address_Line1"]);
            $("#txtAddress2").val(data["Address_Line2"]);
            $("#ddlCountries").val(data["Country_ID"]).trigger('change');
            $("#ddlStates").val(data["State_ID"]);
            $("#txtCity").val(data["City"]);
            $("#txtZip").val(data["ZIP"]);
            $("#txtAttention").val(data["Attention"]);
            $("#txtDeaprtment").val(data["Department"]);
            $("#txtInternalOffice").val(data["Internal_Office"]);
            $("#add_AddressModal").modal({ backdrop: "static", show: true });
            if (id.id == 'edit') {
                $("#btnSave").hide();
                $("#btnUpdate").show();
            }
            else if (id.id == 'view') {
                $("#add_AddressModalBody *").not('#btnCancel').prop('disabled', true);
                $("#btnSave").hide();
                $("#btnUpdate").hide();
            }
        });
       
    };
    $(document).ready(function () {
     
      

        $('#tblAddress').DataTable({
            dom: 'frtip',
            ajax: {
                "url": '/RCApplication/lstAddreses',
                "type": "POST",
                "datatype": "json"
            },
            "pageLength": 5,
            destroy: true,//to over come reintilize prblms
            "columns": [
               {
                   "className": 'details-control',
                   'data': null,
                   "orderable": false,
                   render: function (dd) {
                       return "<i  style='color:indianred;font-weight:bold' class='ti-arrow-circle-right' data-toggle='tooltip' title='Expand/Collpase'></i>";
                   }
               },
                 {
                     'data': null,
                     "orderable": false,
                     render: function (dd) {
                         return "<input type='checkbox' id='chkSelect' class='chkSelect' />";
                     }
                 },

        {
            'data': null,
            "orderable": false,
            render: function (dd) {
                return "<a href='#' id='edit' onclick='PopAddress(this)' ><i style='color:indianred;font-weight:bold' title='Edit' class='ti-pencil '></i></a>";
                //return "<input type='button' class='btn btn-xs btn-rounded btn-info edit' name='name' value='Edit' />";
            }
        }
        , {
            "name": "View",
            'data': null,
            render: function (dd) {
                return "<a href='#' id='view' onclick='PopAddress(this)'><i style='color:indianred;font-weight:bold' title='View' class='ti-eye'></i></a>";
            }
        },
        {
            "name": "NewAddress_ID",
            'data': 'NewAddress_ID'
        }, {
            "name": "Address_Line1",
            'data': 'Address_Line1'
        }, {
            "name": "Address_Line2",
            'data': 'Address_Line2'
        }, {
            "name": "Country_Name",
            'data': 'Country_Name'
        }, {
            "name": "State_Name",
            'data': 'State_Name'
        }, {
            "name": "City",
            'data': 'City'
        }, {
            "name": "ZIP",
            'data': 'ZIP'
        }, {
            "name": "Attention",
            'data': 'Attention'
        }, {
            "name": "Department",
            'data': 'Department'
        }, {
            "name": "Internal_Office",
            'data': 'Internal_Office'
        }
            ]
        });
        function LoadChildData(tblId, Address_ID) {
            var subtable = $('#' + tblId).DataTable({
                //"processing": true,
                "bPaginate": false,
                "searching": false,
                //"serverSide": true,
                "ordering": false,
                "info": false,
                "ajax": {
                    "url": "@Url.Action("addressChildDetails", "RCApplication")",
                    "type": "POST",
                    "data": { AddressId: Address_ID },
                    "datatype": "json"
                },
                "columns": [
         { data: "RCID" },
        { data: "Address_Type" },
        { "data": "Personnel_ID" },
        { "data": "Role" }

        /*and so on, keep adding data elements here for all your columns.*/
                ]
            });
        };
        function childtable(id) {

            return '<table id="' + id + '" class="display">' +
            ' <thead>' +
                ' <tr>' +
                     '<th>  RC ID </th>' +
                     '<th> Addrss Type </th>' +
                     '<th> Personnel ID </th>' +
                     '<th>Role </th>' +
                ' </tr>' +
            ' </thead>' +

        ' </table>'
        }

        function childshow(id, isparent) {
            var tr = $(id).closest('tr');
            var tbl = $('#tblAddress').DataTable();
            var row = tbl.row(tr);
            if (row.child.isShown()) {
                if (isparent && $("#i_expnd").hasClass('ti-arrow-circle-right') || !isparent) {
                    // This row is already open - close it
                    row.child.hide();
                    tr.removeClass('shown');
                    tr[0]["cells"][0].innerHTML = '<i class="ti-arrow-circle-right" title="Expand/Collpase"></i>';
                }
            }
            else {
                if (isparent && $("#i_expnd").hasClass('ti-arrow-circle-down') || !isparent) {
                    // Open this row

                    var ID = row.data()["Address_ID"];
                    var childtblid = 'child_' + row.data()["Address_ID"];
                    row.child(childtable(childtblid)).show();
                    tr.addClass('shown');
                    tr[0]["cells"][0].innerHTML = '<i class="ti-arrow-circle-down" title="Expand/Collpase"></i>';
                    LoadChildData(childtblid, ID);
                }
            }
        }

        $('#tblAddress tbody').on('click', 'td.details-control', function () {
            childshow(this, false);
        });
        $("#i_expnd").click(function () {

            $("#i_expnd").toggleClass("ti-arrow-circle-right");
            $("#i_expnd").toggleClass('ti-arrow-circle-down');
            $("#tblAddress tbody tr .details-control").each(function () {
                childshow(this, true);
            });
        });

        //open add address popup code
        $("#btnAddaddress").click(function () {

            var url = "/RCApplication/OpenaddAddresspopup";

            $("#add_AddressModalBody").load(url, function () {
                $("#btnUpdate").hide();
                $("#btnSave").show();
                $("#add_AddressModal").modal({ backdrop: "static", show: true });
            })
        });

        $("#AddressModalBody").on('click', '.chkSelect', function () {

            $(".chkSelect").prop("checked", false);
            $(this).prop("checked", true);
        });
    });
</script>

<style>
    td.details-control i {
        cursor: pointer;
        color: #e46a76;
        font-weight: bold;
    }
</style>

POC_V2/Areas/RC/Views/Shared/P_Load_PersonalDetails.cshtml
@*@model IEnumerable<dal.SP_GetRCPersonnelDetails_Result>*@

<div class="zxc">
    <table id="tblRcPersonnelDetails" class="display nowrap table table-hover table-responsive table-striped table-bordered" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th><i id="i_expnd" style="color:indianred;font-weight:bold" class="ti-arrow-circle-right" data-toggle="tooltip" title="Expand/Collpase"></i></th>
                <th>Select</th>
                <th>Edit</th>
                <th>View</th>
                <th>Personnel ID</th>
                <th>Salutation</th>
                <th>First Name</th>
                <th>Middle Intital</th>
                <th>Last Name</th>
                <th>Degree</th>
                <th>Medicalspeciality</th>
                <th>Phone</th>
                <th>Phone Ext</th>
                <th>PersonType</th>
                <th>Email</th>
                <th>Fax</th>
                <th>JobTitle</th>
                <th>Comments</th>
                <th>Status</th>
                <th>Status Date</th>
            </tr>
        </thead>
        @*<tbody>
                @foreach (var item in Model)
                {

                    <tr>
                        <td><i id="i_expnd" style="color:indianred;font-weight:bold" class="ti-arrow-circle-right" data-toggle="tooltip" title="Expand/Collpase"></i></td>
                        <td><input type="checkbox" class="chkSelect" /></td>
                        <td><input type="button" class="btn btn-xs btn-rounded btn-info edit " name="name" value="Edit" /></td>
                    </tr>

                }
            </tbody>*@
    </table>
</div>
<div class="offset-4">
    <input type="button" value="Add Person" id="btnAddPerson" class="btn btn-info" />
    <input type="button" id="LoadPerson" value="Load" class="btn btn-info" />
    <input type="button" value="Cancel" class="btn btn-info" data-dismiss-modal="#PersonModal" />
</div>


<script>
    function PopPerson(id) {
      
        var table = $('#tblRcPersonnelDetails').DataTable();
        var tr = id.closest('tr');
        var data = table.row(tr).data();

        var url = "/RCApplication/openAddpersonPopup";

        $("#add_PersonModalBody").load(url, function () {
            $("#txtPhone").mask('(000) 000-0000');
            $("txtStatuDate").prop("readonly", true);
            $("#hiddenId").val(data["ID"]);
            $("#txtPersonId").val(data["Personnel_ID"]);
            $("#txtSalutation").val(data["Salutation"]);
            $("#txtFname").val(data["F_Name"]);
            $("#txtMI").val(data["M_Initials"]);
            $("#txtLastName").val(data["L_Name"]);
            $("#txtPhone").val(data["Phone"]);
            $("#txtFax").val(data["Fax"]);
            $("#txtEmailAddress").val(data["Email"]);
            $("#txtJobTitle").val(data["JobTitle"]);
            $("#txtComments").val(data["Comments"]);
            $("#ddlPersontype").val(data["PersontypeId"]).trigger('change');
            $("#ddlMedicalSpeciality").val(data["MedicalspecialityID"]);
            $("#ddlSuffix").val(data["SuffixID"]);
            $("#txtExt").val(data["Phone_Ext"]);
            // AddressID:("#txtPersonId").val(),
            $("#ddlStatus").val(data["Personnel_StatusID"]);
            if (data["StatusDate"] != null) {
                var date = eval(data["StatusDate"].replace(/\/Date\((\d+)\)\//gi, "new Date($1)"));
                $("#txtStatuDate").val(date.toLocaleDateString());
            }
            if (data["DegreeIDs"] != null) {
                var ids = data["DegreeIDs"].split(',').map(str => str.trim());
                $(".degree").each(function () {
                    if (ids
                    .indexOf($(this).val()) > -1) {
                        $(this).attr('checked', true);
                    }
                })
            }

         
            if (id.id == "view") {
                $("#add_PersonModalBody *").not('#btnCancel').prop("disabled", true);
                $("#btnSavePersonalDetails").hide();
                $("#btnUpdatePersonalDetails").hide();

            }
            else if (id.id == "edit") {
                $("#btnSavePersonalDetails").hide();
                $("#btnUpdatePersonalDetails").show();
            }
            // $("#add_PersonModal").modal("show");
            $('#add_PersonModal').modal({
                backdrop: 'static',
                keyboard: false, // to prevent closing with Esc button (if you want this too)
                show: true
            })
        })
    }
    $(document).ready(function () {

        @*var myData = @Html.Raw(Json.Encode(Model));*@

        $('#tblRcPersonnelDetails').DataTable({
            dom: 'frtip',          
            ajax: {
                "url": "@Url.Action("GetPersonnelDetails", "RCApplication")",
                "type": "POST",
                //"data": { PersonID: ID },
                "datatype": "json"
            },
            destroy: true,//to over come reintilize problems
            "pageLength": 5,
            "columns": [
                {
                    "className": 'details-control',
                    'data': null,
                    "orderable": false,
                    render: function (dd) {
                        return "<i  style='color:indianred;font-weight:bold' class='ti-arrow-circle-right' data-toggle='tooltip' title='Expand/Collpase'></i>";
                    }
                },
    {
        'data': null,
        "orderable": false,
        render: function (dd) {
            return "<input type='checkbox' class='chkSelect' />";
        }
    },

    {
        'data': null,
        "orderable": false,
        render: function (dd) {
            return "<a href='#' id='edit' onclick='PopPerson(this)' ><i style='color:indianred;font-weight:bold' title='Edit' class='ti-pencil '></i></a>";
            //return "<input type='button' class='btn btn-xs btn-rounded btn-info edit' name='name' value='Edit' />";
        }
    }
    , {
        "name": "View",
        'data': null,
        render: function (dd) {
            return "<a href='#' id='view' onclick='PopPerson(this)'><i style='color:indianred;font-weight:bold' title='View' class='ti-eye'></i></a>";
        }
    },
     {
         "name": "Personnel_ID",
         'data': 'Personnel_ID'
     }, {
         "name": "Salutation",
         'data': 'Salutation'
     }, {
         "name": "F_Name",
         'data': 'F_Name'
     }, {
         "name": "M_Initials",
         'data': 'M_Initials'
     }, {
         "name": "L_Name",
         'data': 'L_Name'
     }, {
         "name": "DegreeNames",
         'data': 'DegreeNames'
     }, {
         "name": "Medicalspecialityname",
         'data': 'Medicalspecialityname'
     }, {
         "name": "Phone",
         'data': 'Phone'
     }, {
         "name": "Phone_Ext",
         'data': 'Phone_Ext'
     }, {
         "name": "PersonType",
         'data': 'PersonType'
     },
     {
         "name": "Email",
         'data': 'Email'
     }, {
         "name": "Fax",
         'data': 'Fax'
     }
            , {
                "name": "JobTitle",
                'data': 'JobTitle'
            },
            {
                "name": "Comments",
                'data': 'Comments'
            }
            , {
                "name": "StatusName",
                'data': 'StatusName'
            }, {
                "name": "StatusDate",
                'data': 'StatusDate',
                render: function (dt) {
                    return JsonToDate(dt);
                }
            }
            ]
        });

        function LoadChildData(tblId, ID) {
            var subtable = $('#' + tblId).DataTable({
                //"processing": true,
                "bPaginate": false,
                "searching": false,
                //"serverSide": true,
                "ordering": false,
                "info": false,
                "ajax": {
                    "url": "@Url.Action("PersonnelChildDetails", "RCApplication")",
                    "type": "POST",
                    "data": { PersonID: ID },
                    "datatype": "json"

                },
                "columns": [
        { "data": "RCID" },
        { "data": "Role" },
        { "data": "Address1" },
        { "data": "Address2" },
         { "data": "Attention" },
        { "data": "Internal_Office" },
         { "data": "City" },
        { "data": "State" },
         { "data": "Country" },
        { "data": "ZIP" }
                ]
            });
        }
        function childtable(id) {

            return '<table id="' + id + '" class="display">' +
            ' <thead>' +
                ' <tr>' +
                     '<th>  RCID </th>' +
                     '<th> Role </th>' +
                     '<th> Address1 </th>' +
                     '<th>Address2 </th>' +
                '<th>  Attention </th>' +
                     '<th> Internal Office </th>' +
                     '<th> City </th>' +
                     '<th>State </th>' +
                '<th> Country </th>' +
                     '<th>ZIP </th>' +

                ' </tr>' +
            ' </thead>' +

        ' </table>'
        }

        function childshow(id, isparent) {

            var tr = $(id).closest('tr');
            var tbl = $('#tblRcPersonnelDetails').DataTable();
            var row = tbl.row(tr);
            if (row.child.isShown()) {
                if (isparent && $("#i_expnd").hasClass('ti-arrow-circle-right') || !isparent) {
                    // This row is already open - close it
                    row.child.hide();
                    tr.removeClass('shown');
                    tr[0]["cells"][0].innerHTML = '<i class="ti-arrow-circle-right" title="Expand/Collpase"></i>';
                }
            }
            else {
                if (isparent && $("#i_expnd").hasClass('ti-arrow-circle-down') || !isparent) {
                    // Open this row

                    var ID = row.data()["ID"];
                    var childtblid = 'child_' + row.data()["ID"];
                    row.child(childtable(childtblid)).show();
                    tr.addClass('shown');
                    tr[0]["cells"][0].innerHTML = '<i class="ti-arrow-circle-down" title="Expand/Collpase"></i>';
                    LoadChildData(childtblid, ID);
                }
            }
        }

        $('#tblRcPersonnelDetails tbody').on('click', 'td.details-control', function () {
            childshow(this, false);
        });
        $("#i_expnd").click(function () {

            $("#i_expnd").toggleClass("ti-arrow-circle-right");
            $("#i_expnd").toggleClass('ti-arrow-circle-down');
            $("#tblAddress tbody tr .details-control").each(function () {
                childshow(this, true);
            });
        });


        $("#btnAddPerson").click(function () {

            var url = "/RCApplication/openAddpersonPopup";

            $("#add_PersonModalBody").load(url, function () {
                $("#btnSavePersonalDetails").show();
                $("#btnUpdatePersonalDetails").hide();
                $('#add_PersonModal').modal({
                    backdrop: 'static',
                    keyboard: false, // to prevent closing with Esc button (if you want this too)
                    show: true
                })
                //  $("#add_PersonModal").modal("show");
            })
        });
        $("#PersonModalBody").on('click', '.chkSelect', function () {
            $(".chkSelect").prop("checked", false);
            $(this).prop("checked", true);
        });
    });
</script>


<style>
    td.details-control i {
        cursor: pointer;
        color: #e46a76;
        font-weight: bold;
    }
</style>